### PR TITLE
Replacement for Pull # 14

### PR DESCRIPTION
**Pull request by Shaggs**
As per discussion all code now follows _pep8_ and was done using _flake8_.
Again have removed mapping and browser support its its not required have have removed from the config file as well.

For _TTS.py_ have added an alert sound just so it make sense why the system is talking.

All I have to do now is update some plugin docs and add CFS brigades and appliances to _abbreviations.py_ that will be a long task but am waiting for a list of all appliances and there location.

### CODE REVIEW

**Comment by Shaggs** [comment]
just an update for lpdir so the directions are saved to a text file before printing. without this only the last line is printed.

we have to also work out a way to make a font size for all cups based printing if at all possible e.g size 15 (easy to read and not too big).

**Comment by Shaggs** [comment]
I have just added 398 Brigades now i have to sort out what appliances they have but i guess its a start

**Comment by Shaggs** [comment]
Have now added every brigade and group short code and made it so every brigade has every appliance. this way if there is a change we dont have to update it.

Still missing are dedicated HAZMAT (HAZ) and RESCUE (RESC) appliances as still looking at who has them.

**Comment by Shaggs** [comment]
opps  closed not comment

**Comment by Shaggs** [comment]
Just fount that Rescue is like Bulk Water Carriers there is a space between e.g YANK RESC
so added RESC to the list

**Comment by Shaggs** [comment]
added BWC size

**Comment by Shaggs** [comment]
added BWC Size and found that rescue is set as RESC e.g YANK RESC

**Comment by micolous** [comment]
As discussed, here is a strategy for handling the text replacement relatively quickly without breaking `re`:

https://gist.github.com/micolous/ef69a1f4a6ab08434fe1

**Comment by micolous** [comment]
You can probably also improve on my approach even more.  Technically you don't need a `dict` at all, and you could get away with a 2-dimensional list (or tuple).  This should be faster.

```python
abbreviations = (
  ('ADEL', 'Adelaide'),
  ('FOO', 'FooTown'),
)
```

Then compile and run it with:

```python
abb_re = []
for k, v in abbreviations:
  # extra bracket is important here to make it a tuple
  abb_re.append((re.compile(....), v)

for k, v in abb_re:
  in_str = k.sub(v, in_str)
```

**Comment by Shaggs** [comment]
the code you sent before im using  now and work to a degree. It worked 
once but error is shown as <_sre.SRE_Match object at 0x06E19DA0>

so looking into as we speak

**Comment by Shaggs** [comment]
error <_sre.SRE_Match object at 0x0254ADA0> means is not in the dict 
although it is. so back to the drawing board :)

**Comment by Shaggs** [comment]
removed appliances die to the difficulty of coding so many RE statements.  so each user can do there own appliances

**Comment by Shaggs** [comment]
Have just updated a few thing and added a poor mans logging. Have removed pygame as when using py2exe there was a mixer error so was easier to get the OS to hand it.

One day @micolous you might add my name to the banner when the program starts but ive done it for you this time :P

**Comment by Shaggs** [comment]
@micolous As you can see I'm starting to improve in python and think your master branch is getting a bit behind.

today I've made some more changes and improvements
1) removed "napping...." text.
2) added some colour using CLINT
3) added support to parse SES (State Emergency Services) pages
4) fixed the winprint plugin as there was an issue with the date time and whilst there I made the pager message easier to read (feedback from a few users)
5) Updated the display  plugin for easy reading also.
6) My main achievement fixing the fragmented messages when using the PDW feed. I also removed any text that was not in the the flexcode file this way the test pager and private pager messages are not shown
7) Added custom font size to display pager message

well that's it for now

**Pull request closed without merging**
